### Site Settings ###
title               : Rahmad Alamsyah Nazaruddin
description         : >-                               # >- means to ignore newlines until "url:"
  Focus on Web development and love share with others. Hit me a Message if any help or just ask randomly :)

url                 : ""                                   # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                                   # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : alamnzr123/alamnzr123.github.io  # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2 # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Rahmad Alamsyah Nazaruddin
  image             : /assets/pic.jpg
# behance           : your_username
# dribbble          : your_username
  email             : nzr.rahmad@gmail.com
# facebook          : your_username
  github            : alamnzr123
# gitlab            : your_username
  instagram         : alamnzr
  linkedin          : rahmadalamsyahnazaruddin
  medium            : nzr.rahmad
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 12684030
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"

### Posts Permalink ###
permalink: blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock